package io.cdap.wrangler.parser;

import io.cdap.wrangler.api.parser.ByteSize;
import io.cdap.wrangler.api.parser.ColumnName;
import io.cdap.wrangler.api.parser.DirectivesBaseVisitor;
import io.cdap.wrangler.api.parser.DirectivesParser;
import io.cdap.wrangler.api.parser.Identifier;
import io.cdap.wrangler.api.parser.Numeric;
import io.cdap.wrangler.api.parser.TextList;
import io.cdap.wrangler.api.parser.TimeDuration;
import io.cdap.wrangler.api.parser.Token;
import io.cdap.wrangler.api.parser.TokenGroup;

/**
 * Implementation of visitor pattern for traversing the parse tree generated by ANTLR.
 * This class extends the base visitor generated from the grammar.
 */
public class DirectivesVisitor extends DirectivesBaseVisitor<Token> {

  // Original methods omitted for brevity...

  /**
   * Visits a byte size argument in the parse tree.
   *
   * @param ctx The parse tree context.
   * @return A ByteSize token representing the byte size value.
   */
  @Override
  public Token visitByteSizeArg(DirectivesParser.ByteSizeArgContext ctx) {
    return new ByteSize(ctx.BYTE_SIZE().getText());
  }

  /**
   * Visits a time duration argument in the parse tree.
   *
   * @param ctx The parse tree context.
   * @return A TimeDuration token representing the time duration value.
   */
  @Override
  public Token visitTimeDurationArg(DirectivesParser.TimeDurationArgContext ctx) {
    return new TimeDuration(ctx.TIME_DURATION().getText());
  }

  /**
   * Visits a value in the parse tree, which could be of various token types including the new ones.
   *
   * @param ctx The parse tree context.
   * @return The appropriate token based on the context.
   */
  @Override
  public Token visitValue(DirectivesParser.ValueContext ctx) {
    if (ctx.IDENTIFIER() != null) {
      return new Identifier(ctx.IDENTIFIER().getText());
    } else if (ctx.STRING() != null) {
      String text = ctx.STRING().getText();
      return new io.cdap.wrangler.api.parser.Text(text.substring(1, text.length() - 1));
    } else if (ctx.NUMERIC() != null) {
      return new Numeric(ctx.NUMERIC().getText());
    } else if (ctx.BYTE_SIZE() != null) {
      return new ByteSize(ctx.BYTE_SIZE().getText());
    } else if (ctx.TIME_DURATION() != null) {
      return new TimeDuration(ctx.TIME_DURATION().getText());
    }
    return null;
  }

  /**
   * Visits arguments in the parse tree and converts them to a TokenGroup.
   *
   * @param ctx The parse tree context.
   * @return A TokenGroup containing all the processed tokens.
   */
  @Override
  public Token visitArguments(DirectivesParser.ArgumentsContext ctx) {
    TokenGroup group = new TokenGroup();
    for (DirectivesParser.ArgumentContext argCtx : ctx.argument()) {
      Token token = visit(argCtx);
      if (token != null) {
        group.add(token);
      }
    }
    return group;
  }
}
